show test networks boolean
MetaMask/core pull request #1418
Opened 2023-06-08 10:48 UTC by tommasini

## Description

## Changes
- ADDED
Boolean for show test networks on the preferences controller. 

## References

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation for new or updated code as appropriate (note: this will usually be JSDoc)
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

2023-06-08 11:55 UTC, Mrtenz requested changes

2023-06-08 11:55 UTC, Mrtenz commented on packages/preferences-controller/src/PreferencesController.test.ts
> +  it('shoudl set showTestNetworks', () => {
```suggestion

  it('should set showTestNetworks', () => {
```

2023-06-08 16:51 UTC, mcmire approved these changes
Love those small PRs!

2023-06-09 20:42 UTC, Mrtenz approved these changes

2023-06-29 10:17 UTC, merged