Add getEncryptionPublicKey on KeyringController
MetaMask/core pull request #1569
Opened 2023-08-01 14:54 UTC by cryptodev-2s

## Description

This PR adds the `getEncryptionPublicKey` method on `KeyringController`.

This method calls the homonym `EthKeyringController` method, which returns the encryption public key of the specified address.

## Changes

- **ADDED**: `getEncryptionPublicKey` method

## References

* Fixes: #1556

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation for new or updated code as appropriate (note: this will usually be JSDoc)
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

2023-08-01 20:50 UTC, mcmire reviewed
Is there a way we can add tests for this? Perhaps we can take inspiration from the corresponding test in `eth-keyring-controller`: https://github.com/MetaMask/KeyringController/blob/12e3a2017a9f9b76e10497d93746deeefe3e190b/src/KeyringController.test.ts#L1142

2023-08-02 11:07 UTC, mikesposito requested changes

2023-08-02 11:07 UTC, mikesposito commented on packages/keyring-controller/src/KeyringController.ts
> +   * persisted in the vault.
We don't need to deprecate this one, as the client calling this method will not have direct access to the underlying EthKeyringController or Keyring.

Moreover, `this.#keyring.getEncryptionPublicKey(account)` does not apply any change to the controller state

2023-08-02 11:07 UTC, mikesposito commented on packages/keyring-controller/src/KeyringController.ts
> +   * @returns Promise resolving to encyption public key of the `account` if one exists.
Nit: we can specify that this method throws an exception when there's no keyring managing that address and when the keyring does not support public key encryption:

```suggestion
   * @returns Promise resolving to encyption public key of the `account` if one exists.
   * @throws If the `account` does not exist or does not support the `getEncryptionPublicKey` method
```

2023-08-02 13:33 UTC, mikesposito reviewed
Looks good! I think we just miss an optional argument

2023-08-02 13:33 UTC, mikesposito commented on packages/keyring-controller/src/KeyringController.ts
> +  async getEncryptionPublicKey(account: string): Promise<string> {
We should also support an optional argument `opts?: Record<string, unknown>` argument to pass to `this.#keyring.getEncryptionPublicKey`

See: https://github.com/MetaMask/KeyringController/blob/main/src/KeyringController.ts#L467

2023-08-02 13:40 UTC, mikesposito approved these changes

2023-08-02 13:44 UTC, merged