Refactor: Throw standardized RPC errors using `eth-rpc-errors` when validation fails adding transaction
MetaMask/core pull request #1690
Opened 2023-09-20 10:05 UTC by vinistevam

## Explanation

This PR aims to update the `TransactionController` to throw standardised `ethErrors.rpc.invalidParams` errors using the `eth-rpc-errors` package that will ensure they are standardised and more easily parsed and recognised by the dApps.

The extension `TransactionController` uses the `eth-rpc-errors` package to throw standardised errors when validation fails. This update is a part of the ongoing TransactionController unification effort.

## References

## Changelog

### `@metamask/transaction-controller`

- **CHANGED**: update `validateTxParams` to throw standardised errors using the `eth-rpc-errors` package.

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

2023-09-20 10:23 UTC, OGPoyraz approved these changes

2023-09-21 21:07 UTC, matthewwalsh0 commented
> `eth-rpc-errors` is deprecated - would it be possible to standardize directly on updated and maintained `@metamask/rpc-errors`?
> 
> There is an open draft PR for `@metamask/rpc-errors` update here:
> 
> * [deps: Bump `@metamask/{eth-json-rpc-provider,rpc-errors,utils}`  #1653](https://github.com/MetaMask/core/pull/1653)

This makes sense to me assuming it's functionally identical and the resulting exception are the same?

The goal here is to align with the extension so if this diverges further, it may be best to update the package down the line.

2023-09-22 09:08 UTC, Mrtenz requested changes
Please use `@metamask/rpc-errors`.

2023-09-25 09:42 UTC, vinistevam commented on packages/transaction-controller/package.json
> +    "@metamask/rpc-errors": "^5.1.1",
Bumped `@metamask/rpc-errors` to v6 :pray:

2023-09-26 11:11 UTC, FrederikBolding submitted a review, later dismissed

2023-09-27 07:08 UTC, merged