feat: add types for bridge txs
MetaMask/core pull request #4714
Opened 2024-09-18 18:15 UTC by infiniteflower

## Explanation

## References

## Changelog

### `@metamask/package-a`

- **<CATEGORY>**: Your change here
- **<CATEGORY>**: Your change here

### `@metamask/package-b`

- **<CATEGORY>**: Your change here
- **<CATEGORY>**: Your change here

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

2024-09-26 15:27 UTC, matthewwalsh0 requested changes

2024-09-26 15:27 UTC, matthewwalsh0 commented on packages/transaction-controller/src/types.ts
> +   * A transaction that bridges tokens to a different chain through Metamask Brige.
```suggestion
   * A transaction that bridges tokens to a different chain through Metamask Bridge.
```

2024-09-26 15:27 UTC, matthewwalsh0 commented on packages/transaction-controller/src/types.ts
> +  bridge = 'bridge',
Alphabetical order?

2024-10-02 20:34 UTC, infiniteflower commented on packages/transaction-controller/src/types.ts
> +  bridge = 'bridge',
Done

2024-10-03 07:50 UTC, matthewwalsh0 approved these changes

2024-10-03 13:54 UTC, merged