Add internal account relationship to first time interaction
MetaMask/core pull request #5024
Opened 2024-12-05 08:48 UTC by OGPoyraz

## Explanation

## References

## Changelog

### `@metamask/package-a`

- **<CATEGORY>**: Your change here
- **<CATEGORY>**: Your change here

### `@metamask/package-b`

- **<CATEGORY>**: Your change here
- **<CATEGORY>**: Your change here

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate
- [ ] I've prepared draft pull requests for clients and consumer packages to resolve any breaking changes

2024-12-05 08:48 UTC, OGPoyraz commented
@metamaskbot publish-preview

2024-12-05 09:17 UTC, OGPoyraz commented
@metamaskbot publish-preview

2024-12-06 12:08 UTC, matthewwalsh0 requested changes

2024-12-06 12:08 UTC, matthewwalsh0 commented on packages/transaction-controller/src/TransactionController.ts
> +      (account) => account.address === to,
Do we usually normalize with lowercase to be safe?

2025-01-06 08:02 UTC, closed without merging