Support transactions from account snaps that should not be published
MetaMask/core pull request #5045
Opened 2024-12-09 19:33 UTC by shane-t

## Explanation

Relates to [this extension PR](https://github.com/MetaMask/metamask-extension/pull/28691)

Should not be merged; this is a demonstration

## References

TBD

## Changelog

### `@metamask/transaction-controller`

- **CHANGED**: Removed coupling of "Update custodial transactions" and MMI
- **ADDED**: Before publish hook now receives raw transaction

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate
- [ ] I've prepared draft pull requests for clients and consumer packages to resolve any breaking changes

2024-12-09 19:58 UTC, shane-t commented
@metamaskbot publish-preview

2025-02-06 12:53 UTC, shane-t commented
@metamaskbot publish-preview

2025-02-06 12:54 UTC, shane-t commented
@metamaskbot publish-preview

2025-02-06 12:55 UTC, shane-t commented
@metamaskbot publish-preview

2025-02-20 16:57 UTC, shane-t commented
@metamaskbot publish-preview

2025-03-04 13:46 UTC, shane-t commented
@metamaskbot publish-preview

2025-03-05 16:50 UTC, shane-t commented
@metamaskbot publish-preview

2025-03-05 17:40 UTC, shane-t commented
@metamaskbot publish-preview

2025-03-06 12:28 UTC, shane-t commented
@metamaskbot publish-preview

2025-03-06 12:29 UTC, shane-t commented
@metamaskbot publish-preview

2025-03-06 17:01 UTC, shane-t commented
@metamaskbot publish-preview

2025-03-18 16:36 UTC, matthewwalsh0 requested changes

2025-03-18 16:36 UTC, matthewwalsh0 commented on packages/transaction-controller/src/TransactionController.ts
> +  private registerMessageHandlers(): void {
Minor, we use `#` for private functions so it's private at runtime also.

We also put private methods at the bottom of the file so all the public ones are easier to find.

2025-03-18 16:36 UTC, matthewwalsh0 commented on packages/transaction-controller/src/TransactionController.ts
> +  private registerMessageHandlers(): void {
Minor, could this be `#registerActionHandlers`?

2025-03-18 16:36 UTC, matthewwalsh0 commented on packages/transaction-controller/src/TransactionController.ts
> +    transactionId,
As there is lots of properties here, could we create a type in `types.ts` such as `UpdateCustodialTransactionRequest` to make it more readable and migrate the JSDoc to the type itself?

2025-03-18 16:36 UTC, matthewwalsh0 commented on packages/transaction-controller/src/TransactionController.ts
> +    if (gasLimit) {
Does the above `pickBy` do the same `undefined` checks? Could we just add all these properties to a new `pickBy` specific to the `txParams`?

2025-03-18 16:36 UTC, matthewwalsh0 commented on packages/transaction-controller/src/types.ts
> -  custodyId?: string;
Minor, to simplify the release. Can we pre-emptively add this to the `CHANGELOG.md`?

2025-03-18 16:36 UTC, matthewwalsh0 commented on packages/transaction-controller/src/TransactionController.ts
> +  ) => Promise<boolean>;
The description mentions `Before publish hook now receives raw transaction`? Was that removed?

2025-03-19 15:29 UTC, shane-t commented on packages/transaction-controller/src/TransactionController.ts
> +  ) => Promise<boolean>;
Well spotted, thank you

2025-03-19 15:30 UTC, shane-t commented on packages/transaction-controller/src/types.ts
> -  custodyId?: string;
Done! I've added it under `Unreleased` - I'm not sure if that's right (I'm only used to fixing up changelogs at the last minute 🙂  )

2025-03-19 15:30 UTC, shane-t commented on packages/transaction-controller/src/TransactionController.ts
> +    if (gasLimit) {
Great idea, ✅

2025-03-19 15:31 UTC, shane-t commented on packages/transaction-controller/src/TransactionController.ts
> +    transactionId,
Excellent point, done

2025-03-31 12:22 UTC, matthewwalsh0 commented on packages/transaction-controller/CHANGELOG.md
> +### Changed
This is the wrong place now, probably a bad merge.

But I also had comments concerning the formatting below, so maybe quickest to remove this and I can add back when we release?

2025-03-31 12:25 UTC, matthewwalsh0 requested changes

2025-03-31 12:25 UTC, matthewwalsh0 commented on packages/transaction-controller/src/types.ts
> + * @param transactionId - The ID of the transaction to update.
Can we move these to the properties themselves rather than JSDoc?

2025-03-31 13:40 UTC, shane-t commented on packages/transaction-controller/src/types.ts
> + * @param transactionId - The ID of the transaction to update.
✅

2025-03-31 13:59 UTC, matthewwalsh0 approved these changes

2025-03-31 13:59 UTC, merged