chore: Remove unused OpenSea key
MetaMask/core pull request #5088
Opened 2024-12-20 04:43 UTC by Gudahtt

## Explanation

Remove unused OpenSea API key. This is a breaking change because of the API/type change, but it's not a functional change since it was already unused.

## References

N/A

## Changelog

See diff

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate
- [ ] I've prepared draft pull requests for clients and consumer packages to resolve any breaking changes
  - I skipped this step in this case because the changes are trivial, despite being breaking.

2024-12-20 07:46 UTC, cryptodev-2s approved these changes
LGTM!

2025-01-06 16:46 UTC, cryptodev-2s approved these changes
LGTM!

2025-01-06 16:55 UTC, salimtb approved these changes

2025-01-06 18:23 UTC, bergeron approved these changes

2025-08-07 12:41 UTC, cryptodev-2s requested changes

2025-08-07 12:41 UTC, cryptodev-2s commented on packages/assets-controllers/CHANGELOG.md
> +### Removed
Nit: this should be moved under Unreleased section

2025-08-07 12:58 UTC, Gudahtt commented on packages/assets-controllers/CHANGELOG.md
> +### Removed
Good catch! I think this happened from rebasing the branch. This has been fixed.

2025-10-03 16:44 UTC, Gudahtt commented
This was done in https://github.com/MetaMask/core/pull/4774 instead

2025-10-03 16:44 UTC, closed without merging