fix(3741): refactor remote-feature-flag controller with generateDeterministicRandomNumber and getMetaMetricsId
MetaMask/core pull request #5097
Opened 2024-12-24 14:27 UTC by DDDDDanica

## Explanation

## References

## Changelog

### `@metamask/package-a`

- **<CATEGORY>**: Your change here
- **<CATEGORY>**: Your change here

### `@metamask/package-b`

- **<CATEGORY>**: Your change here
- **<CATEGORY>**: Your change here

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate
- [ ] I've prepared draft pull requests for clients and consumer packages to resolve any breaking changes

2025-01-06 15:17 UTC, NicolasMassart commented on packages/remote-feature-flag-controller/src/utils/user-segmentation-utils.test.ts
> +  MOBILE_MAX: 'ffffffff-ffff-ffff-ffff-ffffffffffff',
```suggestion
  MOBILE_MIN: '00000000-0000-4000-0000-000000000000',
  MOBILE_MAX: 'ffffffff-ffff-4fff-ffff-ffffffffffff',
```

2025-01-06 15:17 UTC, NicolasMassart commented on packages/remote-feature-flag-controller/src/remote-feature-flag-controller.ts
> +    );
Q: i don't really understand what you did here.
Can you elaborate more on this part please? Is it only to force the return type not to be optional or undefined as the MetaMetrics getMetaMetricsId always return a string even if the signature says it can return undefined?
What would you think about modifying the signature of MetaMetrics.getMetaMetricsId to drop undefined?

2025-01-06 15:37 UTC, DDDDDanica commented on packages/remote-feature-flag-controller/src/remote-feature-flag-controller.ts
> +    );
Yes definitely! We no longer handle undefined values - the signature doesn't actually include undefined. It's about handling both synchronous and asynchronous returns in a type-safe way. 
About modifying MetaMetrics.getMetaMetricsId - it is defined in client side while mobile is async and extension is sync, and we will rely on client side to always give a value back 🙏🏻

2025-01-06 15:39 UTC, DDDDDanica commented on packages/remote-feature-flag-controller/src/utils/user-segmentation-utils.test.ts
> +  MOBILE_MAX: 'ffffffff-ffff-ffff-ffff-ffffffffffff',
good catch ! resolved: 035745fec6ceace455f2be68e554d29a7bca3d34

2025-01-06 17:00 UTC, Gudahtt commented on packages/remote-feature-flag-controller/src/remote-feature-flag-controller.test.ts
> +    getMetaMetricsId: () => Promise<string> | string;
Note that this function is synchronous on both extension and mobile. It's typed as asynchronous on mobile by mistake, but it's not.

2025-01-06 17:05 UTC, Gudahtt commented on packages/remote-feature-flag-controller/src/client-config-api-service/client-config-api-service.ts
> +  public getClient(): ClientType {
What is this method for?

2025-01-06 17:09 UTC, Gudahtt commented on packages/remote-feature-flag-controller/src/utils/user-segmentation-utils.ts
> +    return hash / maxValue;
The "max value" here should be the maximum possible hash value, not the maximum possible integer size. If the max here doesn't match the maximum hash size, then our distribution will be skewed.

2025-01-06 17:15 UTC, Gudahtt requested changes
It's really important that we guarantee a uniform distribution, so that a 1% rollout actually results in 1% of users having a feature enabled (rather than 10% or 99% or 0.001%). I'm requesting changes mainly because this doesn't yet seem guaranteed.

Perhaps we can split this PR in two though? The `getMetraMetricsId` related changes are totally distinct, and much simpler.

2025-01-06 22:55 UTC, DDDDDanica commented on packages/remote-feature-flag-controller/src/remote-feature-flag-controller.test.ts
> +    getMetaMetricsId: () => Promise<string> | string;
Oh that's good to know. 

@joaoloureirop could you make adjustments in your side of implementation when initializing the controller to adapt to synchronous pattern?

changed can be found: 15428dacbc477fd6c49844ad0df5f504aa2ee705

2025-01-07 13:47 UTC, DDDDDanica commented on packages/remote-feature-flag-controller/src/client-config-api-service/client-config-api-service.ts
> +  public getClient(): ClientType {
this one is to get the client type we passed in the service configuration. Then when we can decide which algorithm we use inside `generateDeterministicRandomNumber`

2025-01-07 22:02 UTC, DDDDDanica commented
Addressed separately in 
1. https://github.com/MetaMask/core/pull/5110
2. https://github.com/MetaMask/core/pull/5108

2025-01-07 22:02 UTC, closed without merging

2025-01-08 13:32 UTC, joaoloureirop commented on packages/remote-feature-flag-controller/src/remote-feature-flag-controller.test.ts
> +    getMetaMetricsId: () => Promise<string> | string;
Thanks Mark & Danica. I'll update mobile PR